### ISSUE TITLE
Climate entity doesn't work.

### ISSUE THREAD

**Issue by yhi264** [Haoyu-UT/HomeAssistantNatureRemo#1]
Thank you for your great effort to make custom integration for Nature Remo.
I tried to use and found climate entity doesn't work well.
I attached log file of debug mode.
I hope you will make new version.
[home-assistant_nature_remo_2024-03-13T12-18-35.749Z.log](https://github.com/Haoyu-UT/HomeAssistantNatureRemo/files/14587612/home-assistant_nature_remo_2024-03-13T12-18-35.749Z.log)

**Comment by Haoyu-UT** [comment]
@yhi264, hello! Thanks for reporting the issue. I'm investigating your logs, and I think your air conditioner has some unexpected configurations which are still unsupported by this integration.
Please provide me with more information for a fix, following the instructions below.
1. Install python on any computer with Internet connection
2. Install package _requests_ for python
3. Launch a python interpreter, run the following lines and report the results.
```
import requests
url = "https://api.nature.global/1/appliances"
token = "<replace with your token>"
header = {"Authorization": f"Bearer {token}"}
r = requests.get(url=url, headers=header)
print(r.json())
```

**Comment by Haoyu-UT** [comment]
Or alternatively **update the integration to latest 1.0.3 version**.
Delete all entities already added by this integration.
<img width="1082" alt="image" src="https://github.com/Haoyu-UT/HomeAssistantNatureRemo/assets/69963492/4b92f10c-4855-4596-8bd7-114a8e34cf71">
Restart your HA machine, and call service **Logger: Set level** to set the logging level of this integration to debug. Add the integration again and report with your log.
<img width="1082" alt="image" src="https://github.com/Haoyu-UT/HomeAssistantNatureRemo/assets/69963492/62d215be-c29a-4b37-bed9-51bf879b5e93">

**Comment by yhi264** [comment]
> @yhi264, hello! Thanks for reporting the issue. I'm investigating your logs, and I think your air conditioner has some unexpected configurations which are still unsupported by this integration. Please provide me with more information for a fix, following the instructions below.
> 
> 1. Install python on any computer with Internet connection
> 2. Install package _requests_ for python
> 3. Launch a python interpreter, run the following lines and report the results.
> 
> ```
> import requests
> url = "https://api.nature.global/1/appliances"
> token = "<replace with your token>"
> header = {"Authorization": f"Bearer {token}"}
> r = requests.get(url=url, headers=header)
> print(r.json())
> ```

I tried this method. I attached the result as text file.
I hope it will help you!
[result.txt](https://github.com/Haoyu-UT/HomeAssistantNatureRemo/files/14594850/result.txt)

**Comment by Haoyu-UT** [comment]
Hi, @yhi264! Thanks for the information you provided. Please first remove all entities added by the integration, update the integration to latest 1.0.4 version, restart HA, and add this integration again.
Please let me know if the original issue is resolved, or whether you notice some new issues. Your feedback is very precious because I don't own that many Nature Remo devices, and some bugs are unobservable under my environment.

**Comment by yhi264** [comment]
> Hi, @yhi264! Thanks for the information you provided. Please first remove all entities added by the integration, update the integration to latest 1.0.4 version, restart HA, and add this integration again. Please let me know if the original issue is resolved, or whether you notice some new issues. Your feedback is very precious because I don't own that many Nature Remo devices, and some bugs are unobservable under my environment.

Thank you so much @Haoyu-UT san! I updated to 1.0.4, and everything works fine without any error or warning log. Not only Climate entity but also Energy & Power entity (with Remo E Lite) works perfectly!

**Comment by Haoyu-UT** [comment]
Now marked as closed.
