### ISSUE TITLE
Unable to prepare setup for platform 'nature_remo.climate': Platform not found

### ISSUE THREAD

**Issue by cpadavis2** [Haoyu-UT/HomeAssistantNatureRemo#2]
Hello-

First of all, thank you for creating this integration; it is absolutely amazing. I have recently been experiencing a few bugs where, overnight, the integration would "fail to load." Once I noticed this, I would reload the integration manually, and it would work for 12-24 hours. After a month or so of this, I finally decided that I would try a clean install, and upon completing that, I found the following error populating my logs every 10 min or so. 

2024-06-24 22:37:51.256 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'nature_remo.climate': Platform not found (cannot import name 'override' from 'typing' (/usr/local/lib/python3.11/typing.py)).

Any Idea?

(the actual remo is still reporting just fine and, to my knowledge, has yet to need to be reloaded.)

![Unable to prepare setup for platform](https://github.com/Haoyu-UT/HomeAssistantNatureRemo/assets/86432979/c5624bcf-7bdc-42e3-a957-17c3cce7a3b7)

**Comment by Haoyu-UT** [comment]
Hi @cpadavis2! Thanks for your appreciation and feedback. It seems that you have 2 independent problems; for the latter one I think you have installed a previous version of Home Assistant. I used a feature initially shipped with Python 3.12, while I think you have installed Home Assistant which ships Python 3.11. For this problem, please enable the "show beta versions" option in HACS and try the v1.0.6-test version, or simply upgrade the Home Assistant.

As of the occasional failure problem, I would suggest you provide the full system log once you notice the problem again. I suspect this to be a random network issue, while the recovery process from network issue of the integration may need some improvements. I will look into it.

**Comment by Haoyu-UT** [comment]
@cpadavis2 Hello! A few days have already passed, has your problem been solved? Do you need further help or want to provide more feedback?

**Comment by cpadavis2** [comment]
I apologize for the late reply! It took me a few days to be able to update home assistant and reload my backup (running a container) but as of yesterday that fixed both of the issues!!! I really appreciate your patience and feedback though this, and I apologize that it was as simple as me having to update haha.
